"use client";
import { Inter } from "next/font/google";
import { PrivyProvider } from "@privy-io/react-auth";
import { appID } from "./services/api";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Impact Voice",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivyProvider
          appId={appID}
          config={{
            // Customize Privy's appearance in your app
            appearance: {
              theme: "light",
              accentColor: "#676FFF",
              logo: "https://impact-stream-eight.vercel.app/_next/image?url=%2Fafrica.png&w=256&q=75",
            },
            // Create embedded wallets for users who don't have a wallet
            embeddedWallets: {
              createOnLogin: "users-without-wallets",
            },
            loginMethods: ["email", "wallet", "google", "sms"],
          }}
        >
          {children}
        </PrivyProvider>
      </body>
    </html>
  );
}
